CREATE EVENT clean_old_stock_data
ON SCHEDULE EVERY 1 DAY
STARTS '2026-03-31 03:00:00'
ON COMPLETION NOT PRESERVE
ENABLE
COMMENT '7일이 지난 주식 이력 데이터를 삭제하여 디스크 용량 확보'
DO
BEGIN
    DELETE FROM stock_history
    WHERE recorded_at < DATE_SUB(NOW(), INTERVAL 7 DAY);
END;
